### ISSUE TITLE
todo - general code

### ISSUE THREAD

**Issue by e-dub** [e-dub/DesOptPy#10]
### Code general
- [ ] Opt.g = ["gFreqBallistic"] and Opt.g = "gFreqBallistic"
- [x] variable function for primal and sens
- [x] different way to define design variables with x vector
- [x] add initial step to calc nx, ng and source of algorithm!
- [ ] make all values numpy arrays
- [ ] return arrays!!! not lists, for gradients important!
- [x] remove parameter pyOptAlg = True
- [x] add option, fType min max
- [ ] normalize and denormalize as vector operations? not index assignment?
- [ ] nit for nongrad alg
- [ ] ResultReport
- [ ] sensitivity analysis
- [x] Postprocessing for shadow prices
- [ ] echo or debug level? what is standard?
- [ ] Variable linking?
- [x] Normalization for each design variables or global (currently for each)???
- [x] Normalization for each contraint or global (currently for each)???
- [ ] different normalizations for design variables
- [x] default normlaization for xnorm
- [x] default normlaization for fnorm
- [x] default normlaization for gnorm
- [ ] equality constraints?
- [ ] add range constraints?
- [x] default gtype: upper bound
- [ ] rconval -> rConVal
- [ ] sensivity analysis for gVector
- [ ] mix form of constraints for scalara and vectors, e.g. stressVec and dispScalar
- [ ] add all normalization techniques from DesOptPy1
- [ ] gMax and gMaxIt...
- [ ] stop criteria
- [ ] rename interface wrappers
- [ ] save iteration values as hdf5?
- [ ] force f, g, fNabla, gNabla to be list of strings
