### ISSUE TITLE
todo - new benchmarks and examples

### ISSUE THREAD

**Issue by e-dub** [e-dub/DesOptPy#11]
### Examples
- [x] set up example with SiMuLi
- [x] set up example with EasyBeam
- [ ] example with pyUngewiss
- [ ] set up example with Kratos
- [ ] set up example with Ansys (pyAnsys)
- [x] old DesOptPy examples
- [ ] topology optimization example (Hofer)
- [x] max example (to correct fType)
- [ ] matlab example (see paper Palomba)
